### ISSUE TITLE
None of the lesson references work

### ISSUE THREAD

**Issue by deniseliberton** [zhuoaprilfu/2016-11-14-Washington-DC#1]
Under the syllabus on index.html, none of the lesson Reference links work. It's going to your repo rather than the master software carpentry one. I could put in the individual links for each, but do you know how to change the master site on index.html?

Lines 256, 268, 284.

**Comment by zhuoaprilfu** [comment]
looks you forked the repo. To change on the master site, you can make
changes on here directly:

https://github.com/zhuoaprilfu/2016-11-14-Washington-DC

I added you as a collaborator, which means you can change anything directly
on there.

ZF

**Comment by deniseliberton** [comment]
This was an issue of where the reference links for each lesson section were directing on your index page. The same issue was on my forked copy as on this one, but I figured out the solution and updated the index here.
